# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from messages import OpenApiModelMessages_pb2 as OpenApiModelMessages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15OpenApiMessages.proto\x12\x07OpenApi\x1a\x1aOpenApiModelMessages.proto\"C\n\x19ProtoOAApplicationAuthReq\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x14\n\x0c\x63lientSecret\x18\x02 \x01(\t\"\x1b\n\x19ProtoOAApplicationAuthRes\"<\n%ProtoOAGetAccountListByAccessTokenReq\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x01 \x01(\t\"R\n%ProtoOAGetAccountListByAccessTokenRes\x12)\n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32\x17.OpenApi.ProtoOAAccount\"F\n\x0eProtoOAAccount\x12\x1b\n\x13\x63tidTraderAccountId\x18\x01 \x01(\x03\x12\x17\n\x0f\x61\x63\x63ountCurrency\x18\x02 \x01(\t\"I\n\x15ProtoOAAccountAuthReq\x12\x1b\n\x13\x63tidTraderAccountId\x18\x01 \x01(\x03\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x02 \x01(\t\"4\n\x15ProtoOAAccountAuthRes\x12\x1b\n\x13\x63tidTraderAccountId\x18\x01 \x01(\x03\"\x90\x01\n\x12ProtoOANewOrderReq\x12\x1b\n\x13\x63tidTraderAccountId\x18\x01 \x01(\x03\x12\x10\n\x08symbolId\x18\x02 \x01(\x03\x12\x0e\n\x06volume\x18\x03 \x01(\x03\x12\x11\n\torderType\x18\x04 \x01(\x05\x12\x11\n\ttradeSide\x18\x05 \x01(\x05\x12\x15\n\rclientOrderId\x18\x06 \x01(\t\"\x93\x01\n\x15ProtoOAExecutionEvent\x12\x1b\n\x13\x63tidTraderAccountId\x18\x01 \x01(\x03\x12\x0f\n\x07orderId\x18\x02 \x01(\x03\x12\x12\n\npositionId\x18\x03 \x01(\x03\x12\x13\n\x0b\x65xecutionId\x18\x04 \x01(\x03\x12\x14\n\x0c\x66illedVolume\x18\x05 \x01(\x01\x12\r\n\x05price\x18\x06 \x01(\x01\"Y\n\x16ProtoOAOrderErrorEvent\x12\x1b\n\x13\x63tidTraderAccountId\x18\x01 \x01(\x03\x12\x0f\n\x07orderId\x18\x02 \x01(\x03\x12\x11\n\terrorCode\x18\x03 \x01(\x05\x62\x06proto3')



_PROTOOAAPPLICATIONAUTHREQ = DESCRIPTOR.message_types_by_name['ProtoOAApplicationAuthReq']
_PROTOOAAPPLICATIONAUTHRES = DESCRIPTOR.message_types_by_name['ProtoOAApplicationAuthRes']
_PROTOOAGETACCOUNTLISTBYACCESSTOKENREQ = DESCRIPTOR.message_types_by_name['ProtoOAGetAccountListByAccessTokenReq']
_PROTOOAGETACCOUNTLISTBYACCESSTOKENRES = DESCRIPTOR.message_types_by_name['ProtoOAGetAccountListByAccessTokenRes']
_PROTOOAACCOUNT = DESCRIPTOR.message_types_by_name['ProtoOAAccount']
_PROTOOAACCOUNTAUTHREQ = DESCRIPTOR.message_types_by_name['ProtoOAAccountAuthReq']
_PROTOOAACCOUNTAUTHRES = DESCRIPTOR.message_types_by_name['ProtoOAAccountAuthRes']
_PROTOOANEWORDERREQ = DESCRIPTOR.message_types_by_name['ProtoOANewOrderReq']
_PROTOOAEXECUTIONEVENT = DESCRIPTOR.message_types_by_name['ProtoOAExecutionEvent']
_PROTOOAORDERERROREVENT = DESCRIPTOR.message_types_by_name['ProtoOAOrderErrorEvent']
ProtoOAApplicationAuthReq = _reflection.GeneratedProtocolMessageType('ProtoOAApplicationAuthReq', (_message.Message,), {
  'DESCRIPTOR' : _PROTOOAAPPLICATIONAUTHREQ,
  '__module__' : 'OpenApiMessages_pb2'
  # @@protoc_insertion_point(class_scope:OpenApi.ProtoOAApplicationAuthReq)
  })
_sym_db.RegisterMessage(ProtoOAApplicationAuthReq)

ProtoOAApplicationAuthRes = _reflection.GeneratedProtocolMessageType('ProtoOAApplicationAuthRes', (_message.Message,), {
  'DESCRIPTOR' : _PROTOOAAPPLICATIONAUTHRES,
  '__module__' : 'OpenApiMessages_pb2'
  # @@protoc_insertion_point(class_scope:OpenApi.ProtoOAApplicationAuthRes)
  })
_sym_db.RegisterMessage(ProtoOAApplicationAuthRes)

ProtoOAGetAccountListByAccessTokenReq = _reflection.GeneratedProtocolMessageType('ProtoOAGetAccountListByAccessTokenReq', (_message.Message,), {
  'DESCRIPTOR' : _PROTOOAGETACCOUNTLISTBYACCESSTOKENREQ,
  '__module__' : 'OpenApiMessages_pb2'
  # @@protoc_insertion_point(class_scope:OpenApi.ProtoOAGetAccountListByAccessTokenReq)
  })
_sym_db.RegisterMessage(ProtoOAGetAccountListByAccessTokenReq)

ProtoOAGetAccountListByAccessTokenRes = _reflection.GeneratedProtocolMessageType('ProtoOAGetAccountListByAccessTokenRes', (_message.Message,), {
  'DESCRIPTOR' : _PROTOOAGETACCOUNTLISTBYACCESSTOKENRES,
  '__module__' : 'OpenApiMessages_pb2'
  # @@protoc_insertion_point(class_scope:OpenApi.ProtoOAGetAccountListByAccessTokenRes)
  })
_sym_db.RegisterMessage(ProtoOAGetAccountListByAccessTokenRes)

ProtoOAAccount = _reflection.GeneratedProtocolMessageType('ProtoOAAccount', (_message.Message,), {
  'DESCRIPTOR' : _PROTOOAACCOUNT,
  '__module__' : 'OpenApiMessages_pb2'
  # @@protoc_insertion_point(class_scope:OpenApi.ProtoOAAccount)
  })
_sym_db.RegisterMessage(ProtoOAAccount)

ProtoOAAccountAuthReq = _reflection.GeneratedProtocolMessageType('ProtoOAAccountAuthReq', (_message.Message,), {
  'DESCRIPTOR' : _PROTOOAACCOUNTAUTHREQ,
  '__module__' : 'OpenApiMessages_pb2'
  # @@protoc_insertion_point(class_scope:OpenApi.ProtoOAAccountAuthReq)
  })
_sym_db.RegisterMessage(ProtoOAAccountAuthReq)

ProtoOAAccountAuthRes = _reflection.GeneratedProtocolMessageType('ProtoOAAccountAuthRes', (_message.Message,), {
  'DESCRIPTOR' : _PROTOOAACCOUNTAUTHRES,
  '__module__' : 'OpenApiMessages_pb2'
  # @@protoc_insertion_point(class_scope:OpenApi.ProtoOAAccountAuthRes)
  })
_sym_db.RegisterMessage(ProtoOAAccountAuthRes)

ProtoOANewOrderReq = _reflection.GeneratedProtocolMessageType('ProtoOANewOrderReq', (_message.Message,), {
  'DESCRIPTOR' : _PROTOOANEWORDERREQ,
  '__module__' : 'OpenApiMessages_pb2'
  # @@protoc_insertion_point(class_scope:OpenApi.ProtoOANewOrderReq)
  })
_sym_db.RegisterMessage(ProtoOANewOrderReq)

ProtoOAExecutionEvent = _reflection.GeneratedProtocolMessageType('ProtoOAExecutionEvent', (_message.Message,), {
  'DESCRIPTOR' : _PROTOOAEXECUTIONEVENT,
  '__module__' : 'OpenApiMessages_pb2'
  # @@protoc_insertion_point(class_scope:OpenApi.ProtoOAExecutionEvent)
  })
_sym_db.RegisterMessage(ProtoOAExecutionEvent)

ProtoOAOrderErrorEvent = _reflection.GeneratedProtocolMessageType('ProtoOAOrderErrorEvent', (_message.Message,), {
  'DESCRIPTOR' : _PROTOOAORDERERROREVENT,
  '__module__' : 'OpenApiMessages_pb2'
  # @@protoc_insertion_point(class_scope:OpenApi.ProtoOAOrderErrorEvent)
  })
_sym_db.RegisterMessage(ProtoOAOrderErrorEvent)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTOOAAPPLICATIONAUTHREQ._serialized_start=62
  _PROTOOAAPPLICATIONAUTHREQ._serialized_end=129
  _PROTOOAAPPLICATIONAUTHRES._serialized_start=131
  _PROTOOAAPPLICATIONAUTHRES._serialized_end=158
  _PROTOOAGETACCOUNTLISTBYACCESSTOKENREQ._serialized_start=160
  _PROTOOAGETACCOUNTLISTBYACCESSTOKENREQ._serialized_end=220
  _PROTOOAGETACCOUNTLISTBYACCESSTOKENRES._serialized_start=222
  _PROTOOAGETACCOUNTLISTBYACCESSTOKENRES._serialized_end=304
  _PROTOOAACCOUNT._serialized_start=306
  _PROTOOAACCOUNT._serialized_end=376
  _PROTOOAACCOUNTAUTHREQ._serialized_start=378
  _PROTOOAACCOUNTAUTHREQ._serialized_end=451
  _PROTOOAACCOUNTAUTHRES._serialized_start=453
  _PROTOOAACCOUNTAUTHRES._serialized_end=505
  _PROTOOANEWORDERREQ._serialized_start=508
  _PROTOOANEWORDERREQ._serialized_end=652
  _PROTOOAEXECUTIONEVENT._serialized_start=655
  _PROTOOAEXECUTIONEVENT._serialized_end=802
  _PROTOOAORDERERROREVENT._serialized_start=804
  _PROTOOAORDERERROREVENT._serialized_end=893
# @@protoc_insertion_point(module_scope)
