# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aOpenApiModelMessages.proto\x12\rOpenApi.Model\"\xaa\x01\n\x11ProtoOAMarginRate\x12\x18\n\x10leverageInverted\x18\x01 \x01(\x01\x12\x16\n\x0emarginRateType\x18\x02 \x01(\x05\x12\x12\n\nmarginRate\x18\x03 \x01(\x01\x12\x17\n\x0fmarginRateExtra\x18\x04 \x01(\x01\x12\x1b\n\x13marginRateOvernight\x18\x05 \x01(\x01\x12\x19\n\x11marginRateWeekend\x18\x06 \x01(\x01*\xa8\x03\n\x12ProtoOAPayloadType\x12\x11\n\rPROTO_MESSAGE\x10\x00\x12\x19\n\x15PROTO_HEARTBEAT_EVENT\x10\x32\x12\x32\n-PROTO_OA_GET_ACCOUNT_LIST_BY_ACCESS_TOKEN_REQ\x10\xb4\x10\x12\x32\n-PROTO_OA_GET_ACCOUNT_LIST_BY_ACCESS_TOKEN_RES\x10\xb5\x10\x12\x1e\n\x19PROTO_OA_ACCOUNT_AUTH_REQ\x10\xb6\x10\x12\x1e\n\x19PROTO_OA_ACCOUNT_AUTH_RES\x10\xb7\x10\x12\"\n\x1dPROTO_OA_APPLICATION_AUTH_REQ\x10\xbc\x10\x12\"\n\x1dPROTO_OA_APPLICATION_AUTH_RES\x10\xbd\x10\x12\x1b\n\x16PROTO_OA_NEW_ORDER_REQ\x10\xd1\x0f\x12\x1d\n\x18PROTO_OA_EXECUTION_EVENT\x10\xe6\x0f\x12\x1f\n\x1aPROTO_OA_ORDER_ERROR_EVENT\x10\xe7\x0f\x12\x17\n\x12PROTO_OA_ERROR_RES\x10\xea\x07\x62\x06proto3')

_PROTOOAPAYLOADTYPE = DESCRIPTOR.enum_types_by_name['ProtoOAPayloadType']
ProtoOAPayloadType = enum_type_wrapper.EnumTypeWrapper(_PROTOOAPAYLOADTYPE)
PROTO_MESSAGE = 0
PROTO_HEARTBEAT_EVENT = 50
PROTO_OA_GET_ACCOUNT_LIST_BY_ACCESS_TOKEN_REQ = 2100
PROTO_OA_GET_ACCOUNT_LIST_BY_ACCESS_TOKEN_RES = 2101
PROTO_OA_ACCOUNT_AUTH_REQ = 2102
PROTO_OA_ACCOUNT_AUTH_RES = 2103
PROTO_OA_APPLICATION_AUTH_REQ = 2108
PROTO_OA_APPLICATION_AUTH_RES = 2109
PROTO_OA_NEW_ORDER_REQ = 2001
PROTO_OA_EXECUTION_EVENT = 2022
PROTO_OA_ORDER_ERROR_EVENT = 2023
PROTO_OA_ERROR_RES = 1002


_PROTOOAMARGINRATE = DESCRIPTOR.message_types_by_name['ProtoOAMarginRate']
ProtoOAMarginRate = _reflection.GeneratedProtocolMessageType('ProtoOAMarginRate', (_message.Message,), {
  'DESCRIPTOR' : _PROTOOAMARGINRATE,
  '__module__' : 'OpenApiModelMessages_pb2'
  # @@protoc_insertion_point(class_scope:OpenApi.Model.ProtoOAMarginRate)
  })
_sym_db.RegisterMessage(ProtoOAMarginRate)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTOOAPAYLOADTYPE._serialized_start=219
  _PROTOOAPAYLOADTYPE._serialized_end=643
  _PROTOOAMARGINRATE._serialized_start=46
  _PROTOOAMARGINRATE._serialized_end=216
# @@protoc_insertion_point(module_scope)
